import { EmailBlock } from './types';

export const blockTemplates: Record<string, EmailBlock> = {
  header: {
    type: 'header',
    logoUrl: '',
    logoAlt: 'Logo',
    logoWidth: '150',
    alignment: 'center',
    padding: '20px',
  },
  heading: {
    type: 'heading',
    text: 'Título Principal',
    level: 'h1',
    alignment: 'left',
    color: '#333333',
    fontSize: '32px',
    padding: '20px',
  },
  text: {
    type: 'text',
    content: 'Digite seu texto aqui. Você pode adicionar múltiplos parágrafos e formatar conforme necessário.',
    alignment: 'left',
    color: '#666666',
    fontSize: '16px',
    padding: '20px',
  },
  image: {
    type: 'image',
    url: 'https://via.placeholder.com/600x300',
    alt: 'Imagem',
    width: '100%',
    alignment: 'center',
    padding: '20px',
  },
  button: {
    type: 'button',
    text: 'Clique Aqui',
    url: 'https://example.com',
    alignment: 'center',
    buttonColor: '#0066cc',
    textColor: '#ffffff',
    buttonPadding: '12px 30px',
    borderRadius: '4px',
    padding: '20px',
  },
  divider: {
    type: 'divider',
    color: '#dddddd',
    thickness: '1px',
    width: '100%',
    padding: '20px',
  },
  spacer: {
    type: 'spacer',
    height: '20px',
  },
  'columns-2': {
    type: 'columns-2',
    column1: [],
    column2: [],
    columnGap: '20px',
    padding: '20px',
  },
  'columns-3': {
    type: 'columns-3',
    column1: [],
    column2: [],
    column3: [],
    columnGap: '15px',
    padding: '20px',
  },
  banner: {
    type: 'banner',
    imageUrl: 'https://via.placeholder.com/600x200',
    alt: 'Banner',
    height: 'auto',
  },
  product: {
    type: 'product',
    imageUrl: 'https://via.placeholder.com/300x300',
    name: 'Nome do Produto',
    description: 'Descrição breve do produto',
    price: 'R$ 99,00',
    buttonText: 'Comprar Agora',
    buttonUrl: 'https://example.com',
    padding: '20px',
  },
  social: {
    type: 'social',
    platforms: [
      { name: 'facebook', url: 'https://facebook.com' },
      { name: 'instagram', url: 'https://instagram.com' },
      { name: 'twitter', url: 'https://twitter.com' },
    ],
    alignment: 'center',
    iconSize: '32px',
    padding: '20px',
  },
  footer: {
    type: 'footer',
    content: 'Sua Empresa © 2024. Todos os direitos reservados.<br>Endereço da empresa',
    alignment: 'center',
    color: '#999999',
    fontSize: '14px',
    padding: '20px',
    backgroundColor: '#f4f4f4',
  },
  legal: {
    type: 'legal',
    content: 'Este e-mail foi enviado para você porque está cadastrado em nossa lista. Respeitamos sua privacidade conforme nossa Política de Privacidade.',
    fontSize: '11px',
    color: '#999999',
    padding: '20px',
  },
  unsubscribe: {
    type: 'unsubscribe',
    text: 'Não quer mais receber nossos e-mails?',
    linkText: 'Cancelar inscrição',
    alignment: 'center',
    fontSize: '12px',
    color: '#999999',
    padding: '20px',
  },
};

export const blockCategories = [
  {
    name: 'Estrutura',
    blocks: ['header', 'heading', 'text', 'divider', 'spacer', 'footer'],
  },
  {
    name: 'Conteúdo',
    blocks: ['image', 'button', 'banner', 'product'],
  },
  {
    name: 'Layout',
    blocks: ['columns-2', 'columns-3'],
  },
  {
    name: 'Social & Legal',
    blocks: ['social', 'legal', 'unsubscribe'],
  },
];

export const blockLabels: Record<string, string> = {
  header: 'Cabeçalho/Logo',
  heading: 'Título',
  text: 'Texto',
  image: 'Imagem',
  button: 'Botão',
  divider: 'Divisor',
  spacer: 'Espaçador',
  'columns-2': '2 Colunas',
  'columns-3': '3 Colunas',
  banner: 'Banner',
  product: 'Produto',
  social: 'Redes Sociais',
  footer: 'Rodapé',
  legal: 'Texto Legal',
  unsubscribe: 'Descadastrar',
};
