import { announce, benefits, body, content, couponBox, cta, divider, footer, grid, hero, logo, proof, sectionTitle, steps, urgency, type ReadyTemplate } from "./kit";

export const RELATIONSHIP_TEMPLATES: ReadyTemplate[] = [
  {
    id: "boas-vindas", category: "relacionamento", name: "Boas-vindas / 1ª compra", palette: "dark",
    occasion: "Quem acabou de se cadastrar e ainda não comprou.",
    strategy: "O cupom de primeira compra é o que mais converte na sua loja (cerca de 1 em cada 6 pedidos). Cupom no topo, benefícios para tirar o medo e os mais pedidos para escolher rápido.",
    subjects: ["Bem-vindo(a), {{first_name|cliente}}! Seu desconto de 1ª compra está aqui", "{{first_name|Cliente}}, um presente para o seu primeiro pedido", "Seu cupom de boas-vindas (use hoje)"],
    preheader: "Desconto exclusivo no seu primeiro pedido.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Bem-vindo(a), {{first_name|você}}", title: "Seu primeiro pedido com desconto", sub: "Que bom ter você aqui. Use o cupom abaixo na sua primeira compra.", cta: "Escolher meus produtos" }),
      couponBox(c.palette, { title: "Cupom de boas-vindas", code: "PRIMEIRACOMPRA", desc: "Válido na primeira compra" }),
      benefits(c.palette),
      sectionTitle(c.palette, "Os mais pedidos", "Por onde a maioria começa"),
      grid(c.palette, c.bestsellers, 6),
      proof(c.palette, c),
      cta(c.palette, c, "Usar meu cupom agora"),
      footer(c.palette, c),
    ]),
  },
  {
    id: "pos-compra", category: "relacionamento", name: "Pós-compra (obrigado + indicar)", palette: "light",
    occasion: "Cerca de 7 dias depois da entrega: agradece, pede avaliação e oferece o próximo item.",
    strategy: "Cliente satisfeito é a melhor hora de vender de novo (pedidos com 1 item são a maioria). Agradecimento, o que vem a seguir, pedido de avaliação e itens que combinam.",
    subjects: ["Obrigado pela compra, {{first_name|cliente}}!", "Chegou tudo certo? Conta pra gente", "{{first_name|Cliente}}, complete seu pedido com estes"],
    preheader: "Obrigado pela confiança. Veja o que combina com a sua compra.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Obrigado", title: "Valeu pela confiança, {{first_name|cliente}}", sub: "Sua compra é o que mantém a loja de pé. Esperamos que você ame.", cta: "Avaliar minha compra" }),
      steps(c.palette, [["Preparamos", "com cuidado"], ["Enviamos", "pelo melhor frete"], ["Você curte", "e nos conta"]]),
      body(c.palette, "Chegou tudo certo? Se algo não saiu como esperado, **fale com a nossa equipe de atendimento** pelos canais da loja e resolvemos."),
      divider(c.palette),
      sectionTitle(c.palette, "Combina com o seu pedido", "Quem comprou também levou"),
      grid(c.palette, c.bestsellers, 4),
      cta(c.palette, c, "Ver mais produtos"),
      footer(c.palette, c),
    ]),
  },
  {
    id: "recompra", category: "relacionamento", name: "Hora de repor / recompra", palette: "vibrant",
    occasion: "Cerca de 60 a 75 dias depois da última compra (o prazo mediano de recompra da sua loja é 74 dias).",
    strategy: "Só 12% dos clientes compram de novo, e a segunda compra costuma vir por volta de 74 dias. Este e-mail chega nessa janela com novidades e um motivo para voltar.",
    subjects: ["{{first_name|Cliente}}, já faz um tempo. O que chegou de novo?", "Hora de renovar? Veja as novidades", "Sentimos a sua falta por aqui"],
    preheader: "Novidades e os mais pedidos, de volta pra você.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Faz um tempo", title: "Hora de renovar?", sub: "Desde a sua última compra, a loja ganhou novidades. Dê uma olhada.", cta: "Ver novidades" }),
      sectionTitle(c.palette, "Chegou agora"),
      grid(c.palette, c.newest, 4),
      sectionTitle(c.palette, "Os mais pedidos"),
      grid(c.palette, c.bestsellers, 4),
      couponBox(c.palette, { title: "Presente por voltar", code: "VOLTEI10", desc: "Desconto na sua próxima compra" }),
      cta(c.palette, c, "Voltar à loja"),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "reativacao", category: "relacionamento", name: "Reativação (sentimos sua falta)", palette: "dark",
    occasion: "Clientes sem comprar há 90 dias ou mais.",
    strategy: "Tom pessoal, oferta mais forte que o normal e prazo. É a lista com menos engajamento: curto, direto, um cupom e um botão.",
    subjects: ["{{first_name|Amigo(a)}}, sentimos sua falta", "Voltou? Temos um presente para você", "Faz tempo! Seu cupom especial está aqui"],
    preheader: "Um desconto especial para você voltar.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Sentimos sua falta", title: "Que tal voltar, {{first_name|amigo}}?", sub: "Preparamos uma condição especial só para você.", cta: "Resgatar meu presente" }),
      couponBox(c.palette, { title: "Seu cupom de volta", code: "VOLTOU15", desc: "Desconto especial para clientes que já nos conhecem" }),
      urgency(c.palette, `Vale até ${c.deadline}`),
      sectionTitle(c.palette, "Enquanto você esteve fora"),
      grid(c.palette, c.newest.length ? c.newest : c.bestsellers, 4),
      proof(c.palette, c),
      cta(c.palette, c, "Usar meu cupom"),
      footer(c.palette, c),
    ]),
  },
  {
    id: "aniversario", category: "relacionamento", name: "Aniversário do cliente", palette: "vibrant",
    occasion: "Enviado no aniversário ou durante o mês do aniversário.",
    strategy: "Mensagem pessoal e presente simples de usar. Alta abertura porque fala do cliente, não da loja.",
    subjects: ["Parabéns, {{first_name|cliente}}! 🎉 Tem presente pra você", "Feliz aniversário! Seu presente chegou", "{{first_name|Cliente}}, hoje o dia é seu"],
    preheader: "Um presente de aniversário só seu.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Seu dia é especial", title: "Parabéns, {{first_name|cliente}}!", sub: "Para comemorar com você, separamos um presente: um desconto exclusivo no seu mês de aniversário.", cta: "Resgatar meu presente" }),
      couponBox(c.palette, { title: "Presente de aniversário", code: "NIVER10", desc: "Use no mês do seu aniversário" }),
      sectionTitle(c.palette, "Escolha o seu presente"),
      grid(c.palette, c.bestsellers, 4),
      cta(c.palette, c, "Ir às compras"),
      footer(c.palette, c),
    ]),
  },
  {
    id: "vip", category: "relacionamento", name: "Clientes VIP (acesso antecipado)", palette: "gold",
    occasion: "Quem mais compra: lançamentos antes do público e condição exclusiva.",
    strategy: "Exclusividade e reconhecimento. Os melhores clientes respondem a acesso antecipado mais do que a desconto.",
    subjects: ["{{first_name|Cliente}}, você tem acesso antecipado", "VIP: veja antes de todo mundo", "Exclusivo para você: novidades e condição especial"],
    preheader: "Antes de abrir ao público. Só para clientes VIP.",
    build: (c) => content(c.palette, [
      announce(c.palette, "Exclusivo para clientes VIP"),
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Clientes VIP", title: "Você chega primeiro", sub: "Acesso antecipado às novidades e uma condição que só quem compra com a gente tem.", cta: "Ver em primeira mão" }),
      couponBox(c.palette, { title: "Seu benefício VIP", code: "VIP20", desc: "Exclusivo para clientes VIP" }),
      sectionTitle(c.palette, "Antes de todo mundo"),
      grid(c.palette, c.newest.length ? c.newest : c.bestsellers, 6),
      cta(c.palette, c, "Entrar no acesso VIP"),
      footer(c.palette, c),
    ]),
  },
];
