import { announce, benefits, content, couponBox, cta, divider, feature, footer, grid, hero, logo, proof, sectionTitle, steps, urgency, type ReadyTemplate } from "./kit";

export const SALES_TEMPLATES: ReadyTemplate[] = [
  {
    id: "promo-relampago", category: "vendas", name: "Promoção relâmpago", palette: "vibrant",
    occasion: "Oferta com prazo curto para vender estoque ou movimentar a base.",
    strategy: "Botão acima da dobra, prazo claro, os mais vendidos como prova social, urgência repetida e uma faixa de confiança antes do botão final.",
    subjects: ["⚡ {{first_name|Ei}}, preços que não voltam (por pouco tempo)", "Relâmpago: os mais pedidos com desconto (acaba logo)", "{{first_name|Cliente}}, corre: oferta termina em breve"],
    preheader: "Os mais vendidos com preço especial. Estoque limitado.",
    build: (c) => content(c.palette, [
      announce(c.palette, `⚡ Oferta relâmpago · só até ${c.deadline}`),
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Oferta relâmpago", title: "Preços que não voltam", sub: `Os mais pedidos da loja com condição especial, só até ${c.deadline} ou enquanto durar o estoque.`, cta: "Aproveitar agora" }),
      sectionTitle(c.palette, "Os mais pedidos", "Os que mais saíram nas últimas semanas"),
      grid(c.palette, c.bestsellers, 6),
      urgency(c.palette, `Termina em ${c.deadline}`),
      cta(c.palette, c, "Ver todas as ofertas"),
      proof(c.palette, c),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "black-friday", category: "vendas", name: "Black Friday", palette: "blackfriday",
    occasion: "Black Friday e semana de ofertas (novembro).",
    strategy: "Fundo preto com amarelo (leitura imediata de Black), cupom em destaque, grade grande de campeões de venda e escassez explícita. Novembro é o seu maior mês de pedidos.",
    subjects: ["🖤 BLACK FRIDAY começou, {{first_name|cliente}}", "Black Friday: o maior desconto do ano está aqui", "Último aviso: a Black Friday não espera"],
    preheader: "Maior desconto do ano. Estoque limitado, sem reposição.",
    build: (c) => content(c.palette, [
      announce(c.palette, "Black Friday · só enquanto durar o estoque"),
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "O maior desconto do ano", title: "Black Friday", titleSize: "48px", sub: "Desconto de verdade nos mais vendidos. Quando acabar, acabou.", cta: "Entrar na Black Friday" }),
      couponBox(c.palette, { title: "Cupom Black Friday", code: "BLACK10", desc: "Use no carrinho para liberar o desconto extra" }),
      sectionTitle(c.palette, "Campeões de venda"),
      grid(c.palette, c.bestsellers, 6),
      urgency(c.palette, `Oferta válida até ${c.deadline}`),
      cta(c.palette, c, "Quero minha Black Friday"),
      proof(c.palette, c),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "pre-black", category: "vendas", name: "Pré-Black (lista VIP)", palette: "gold",
    occasion: "Dias antes da Black Friday, para quem já comprou ou está na lista.",
    strategy: "Sensação de acesso antecipado antes do público geral, cupom exclusivo e passo a passo de 3 etapas para tirar a dúvida de como aproveitar.",
    subjects: ["{{first_name|Cliente}}, você entra antes na Black Friday", "Acesso antecipado: Black Friday só para a nossa lista", "Pré-Black liberada: seu cupom exclusivo está aqui"],
    preheader: "Cupom exclusivo antes de abrir para todo mundo.",
    build: (c) => content(c.palette, [
      announce(c.palette, "Acesso antecipado · só para a nossa lista"),
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Pré-Black", title: "Você entra antes", sub: "As ofertas da Black Friday já estão liberadas para você, antes de abrir para o público.", cta: "Entrar agora" }),
      couponBox(c.palette, { title: "Seu cupom antecipado", code: "PREBLACK10", desc: "Exclusivo para quem está na lista" }),
      steps(c.palette, [["Escolha", "seus produtos"], ["Use o cupom", "no carrinho"], ["Receba", "em casa"]]),
      sectionTitle(c.palette, "Para começar"),
      grid(c.palette, c.bestsellers, 4),
      urgency(c.palette, `Acesso antecipado até ${c.deadline}`),
      cta(c.palette, c, "Aproveitar antes de todo mundo"),
      proof(c.palette, c),
      footer(c.palette, c),
    ]),
  },
  {
    id: "desconto-progressivo", category: "vendas", name: "Leve mais, pague menos", palette: "dark",
    occasion: "Aumentar o número de peças por pedido (desconto por quantidade).",
    strategy: "Hoje o pedido médio tem menos de 2 itens. A escada de desconto (2 peças, 3 peças) mostra o ganho de levar mais e empurra o segundo item.",
    subjects: ["Leve 2 ou mais e pague menos, {{first_name|cliente}}", "Quanto mais você leva, menos você paga", "Monte seu pedido: desconto progressivo liberado"],
    preheader: "2 peças já têm desconto. 3 peças, mais ainda.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Desconto progressivo", title: "Leve mais, pague menos", sub: "Quanto mais peças no carrinho, maior o desconto no pedido.", cta: "Montar meu pedido" }),
      { type: "columns-2", columnGap: "12px", padding: "26px 16px 10px",
        column1: [{ type: "text", content: "**2 peças**\n\n**10% OFF**", alignment: "center", color: c.palette.text, fontSize: "20px", lineHeight: "1.4", backgroundColor: c.palette.card, borderRadius: "10px", padding: "22px 10px" }],
        column2: [{ type: "text", content: "**3 peças ou mais**\n\n**15% OFF**", alignment: "center", color: c.palette.highlight, fontSize: "20px", lineHeight: "1.4", backgroundColor: c.palette.card, borderRadius: "10px", padding: "22px 10px" }] },
      sectionTitle(c.palette, "Combine com os mais pedidos"),
      grid(c.palette, c.bestsellers, 6),
      cta(c.palette, c, "Ir para o carrinho"),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "ultimas-unidades", category: "vendas", name: "Últimas unidades", palette: "light",
    occasion: "Produtos com estoque baixo e sem previsão de reposição.",
    strategy: "Escassez real vende: título curto e direto, grade dos itens e um único botão, sem distrações.",
    subjects: ["{{first_name|Cliente}}, está acabando", "Últimas unidades: não fica pra depois", "Esses modelos podem não voltar"],
    preheader: "Estoque baixo, sem previsão de reposição.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Estoque baixo", title: "Está acabando", sub: "Estes modelos estão nas últimas unidades e ainda não há previsão de volta.", cta: "Garantir o meu" }),
      grid(c.palette, c.bestsellers, 6),
      urgency(c.palette, "Quando acabar, acabou"),
      cta(c.palette, c, "Ver o que ainda tem"),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "volta-estoque", category: "vendas", name: "Voltou ao estoque", palette: "dark",
    occasion: "Reposição de itens que esgotaram e tinham procura.",
    strategy: "Reconhece o desejo do cliente (você pediu), reduz a decisão a um clique e avisa que pode esgotar de novo.",
    subjects: ["Voltou! O que você queria está de volta", "Reposição: garanta antes de esgotar de novo", "{{first_name|Cliente}}, chegou de novo"],
    preheader: "Os queridinhos que esgotaram estão de volta.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "De volta ao estoque", title: "Voltou. Corre.", sub: "Os queridinhos que esgotaram estão de volta. Garanta o seu antes que acabe de novo.", cta: "Ver o que voltou" }),
      grid(c.palette, c.bestsellers, 6),
      urgency(c.palette, "Pode esgotar de novo"),
      cta(c.palette, c, "Garantir agora"),
      proof(c.palette, c),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "lancamento", category: "vendas", name: "Lançamento / coleção nova", palette: "dark",
    occasion: "Novos produtos, coleção ou drop.",
    strategy: "Um produto em destaque com imagem grande e texto curto, seguido de grade das novidades. Foco primeiro, variedade depois.",
    subjects: ["Acabou de chegar: coleção nova", "{{first_name|Cliente}}, você viu o que chegou?", "Lançamento: seja o primeiro a vestir"],
    preheader: "Peças novas disponíveis agora.",
    build: (c) => content(c.palette, [
      announce(c.palette, "Novidade · acabou de chegar"),
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Lançamento", title: "Coleção nova", sub: "Peças que acabaram de chegar. Quem pega primeiro, escolhe melhor.", cta: "Ver lançamentos" }),
      c.newest[0] ? feature(c.palette, c.newest[0], { title: c.newest[0].name, text: `A peça de destaque da coleção.\n**${c.newest[0].price}**`, button: "Quero esse" }) : [],
      sectionTitle(c.palette, "Mais novidades"),
      grid(c.palette, c.newest.slice(c.newest[0] ? 1 : 0), 6),
      divider(c.palette),
      cta(c.palette, c, "Ver a coleção completa"),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
];
