import { announce, benefits, body, content, couponBox, cta, divider, feature, footer, grid, hero, logo, proof, sectionTitle, urgency, type ReadyTemplate } from "./kit";

export const SEASONAL_TEMPLATES: ReadyTemplate[] = [
  {
    id: "natal", category: "datas", name: "Natal (presentes)", palette: "natal",
    occasion: "Novembro e dezembro: campanha de presentes de fim de ano.",
    strategy: "Dezembro é o segundo maior mês de pedidos da loja. Verde e vermelho dão clima na hora, o cupom de Natal puxa a decisão e o aviso de prazo cria urgência real.",
    subjects: ["🎄 Presentes de Natal com desconto, {{first_name|cliente}}", "Natal chegando: garanta o presente a tempo", "Seu cupom de Natal está aqui"],
    preheader: "Presentes que fazem a diferença, com cupom de Natal.",
    build: (c) => content(c.palette, [
      announce(c.palette, "🎄 Natal · peça cedo para receber a tempo"),
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Especial de Natal", title: "Presentes que fazem a diferença", sub: "Escolha com calma e receba a tempo. Tem cupom de Natal para você.", cta: "Ver presentes" }),
      couponBox(c.palette, { title: "Cupom de Natal", code: "NATAL10", desc: "Desconto no seu presente" }),
      sectionTitle(c.palette, "Campeões de presente", "O que mais sai nesta época"),
      grid(c.palette, c.bestsellers, 6),
      urgency(c.palette, "Confira o prazo de entrega no site antes de fechar"),
      cta(c.palette, c, "Escolher meu presente"),
      proof(c.palette, c),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "dia-de-presentear", category: "datas", name: "Dia de presentear (Namorados, Pais, Mães)", palette: "love",
    occasion: "Datas de presente: Dia dos Namorados, Dia dos Pais, Dia das Mães e similares. Troque o nome da data.",
    strategy: "Guia de presentes por data. O cliente chega com a intenção pronta; o e-mail só precisa dar boas opções, prazo e um botão.",
    subjects: ["Ainda dá tempo: presentes para quem você ama", "{{first_name|Cliente}}, o presente certo está aqui", "Guia de presentes: escolha em 2 minutos"],
    preheader: "Ideias de presente com envio para todo o Brasil.",
    build: (c) => content(c.palette, [
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Nome da data aqui", title: "Presenteie quem você ama", sub: "Escolhemos os presentes mais pedidos para facilitar a sua vida.", cta: "Ver ideias de presente" }),
      sectionTitle(c.palette, "Os mais presenteados"),
      grid(c.palette, c.bestsellers, 6),
      urgency(c.palette, "Peça com antecedência para receber a tempo"),
      cta(c.palette, c, "Ver todos os presentes"),
      benefits(c.palette),
      footer(c.palette, c),
    ]),
  },
  {
    id: "reinauguracao", category: "datas", name: "Reinauguração / aniversário da loja", palette: "blackfriday",
    occasion: "Volta da loja, reinauguração ou aniversário da marca.",
    strategy: "Evento de marca: celebra, dá um motivo para visitar agora (cupom) e mostra o que mudou. Bom para reacender uma base que ficou parada.",
    subjects: ["Estamos de volta, {{first_name|cliente}}! Condição de reinauguração", "A loja reabriu: veja as novidades e o cupom", "Voltamos com tudo (e com desconto)"],
    preheader: "Novidades e cupom de reinauguração.",
    build: (c) => content(c.palette, [
      announce(c.palette, "Reinauguração · condição especial"),
      logo(c.palette, c),
      hero(c.palette, c, { eyebrow: "Estamos de volta", title: "Reinauguração", titleSize: "46px", sub: "A loja voltou renovada, com novidades e um cupom para comemorar com você.", cta: "Conhecer a loja nova" }),
      couponBox(c.palette, { title: "Cupom de reinauguração", code: "VOLTAMOS10", desc: "Válido por tempo limitado" }),
      c.newest[0] ? feature(c.palette, c.newest[0], { title: "O que chegou", text: `Uma das novidades da loja.\n**${c.newest[0].price}**`, button: "Quero ver" }) : [],
      sectionTitle(c.palette, "Os mais pedidos"),
      grid(c.palette, c.bestsellers, 6),
      body(c.palette, "Obrigado por continuar com a gente. Foi por você que voltamos."),
      divider(c.palette),
      cta(c.palette, c, "Ir às compras"),
      proof(c.palette, c),
      footer(c.palette, c),
    ]),
  },
];
