-- =============================================================================
-- SPY PRO CRM - VPS DEPLOY: TABELAS BLING
-- =============================================================================

CREATE TABLE public.bling_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  created_by_user_id uuid,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expires_at timestamptz NOT NULL,
  refresh_expires_at timestamptz,
  scopes text[],
  status text DEFAULT 'connected',
  bling_user_id text,
  bling_user_name text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  bling_company_id text
);
CREATE UNIQUE INDEX bling_connections_tenant_id_idx ON public.bling_connections(tenant_id);

CREATE TABLE public.bling_situacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  situacao_id integer NOT NULL,
  nome text NOT NULL,
  id_herdado integer,
  cor text,
  modulo_id integer NOT NULL,
  modulo_nome text,
  synced_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(integration_id, situacao_id)
);

CREATE TABLE public.bling_code_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  mapping_type text NOT NULL,
  original_code text NOT NULL,
  display_name text NOT NULL,
  color text,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(integration_id, mapping_type, original_code)
);

CREATE TABLE public.bling_customers (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  bling_id bigint NOT NULL,
  nome text NOT NULL,
  fantasia text,
  tipo_pessoa text,
  cpf_cnpj text,
  ie text,
  email text,
  telefone text,
  celular text,
  endereco jsonb,
  situacao text,
  data_inclusao timestamptz,
  raw_data jsonb,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  synced_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  data_nascimento date,
  sexo text,
  naturalidade text,
  rg text,
  orgao_emissor text,
  UNIQUE(bling_id, integration_id)
);

CREATE TABLE public.bling_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  bling_id bigint NOT NULL,
  numero text NOT NULL,
  data_criacao timestamptz,
  data_modificacao timestamptz,
  situacao_id integer,
  situacao_nome text,
  cliente_id bigint,
  cliente_nome text,
  cliente_cpf_cnpj text,
  cliente_email text,
  cliente_telefone text,
  valor_total numeric,
  valor_desconto numeric,
  valor_frete numeric,
  valor_produtos numeric,
  forma_pagamento text,
  forma_envio text,
  observacoes text,
  observacoes_internas text,
  endereco_entrega jsonb,
  loja_id bigint,
  loja_nome text,
  raw_data jsonb,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  synced_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  numero_loja text,
  data_saida timestamptz,
  data_prevista timestamptz,
  outras_despesas numeric DEFAULT 0,
  numero_pedido_compra text,
  categoria_id bigint,
  nota_fiscal_id bigint,
  total_icms numeric DEFAULT 0,
  total_ipi numeric DEFAULT 0,
  vendedor_id bigint,
  intermediador_cnpj text,
  intermediador_nome_usuario text,
  taxa_comissao numeric DEFAULT 0,
  custo_frete numeric DEFAULT 0,
  valor_base numeric DEFAULT 0,
  frete_por_conta integer,
  quantidade_volumes integer,
  peso_bruto numeric,
  prazo_entrega integer,
  transportador_id bigint,
  transportador_nome text,
  etiqueta jsonb,
  volumes jsonb,
  parcelas jsonb,
  UNIQUE(bling_id, integration_id)
);

CREATE TABLE public.bling_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES public.bling_orders(id) ON DELETE CASCADE,
  bling_id bigint,
  produto_id bigint,
  produto_nome text,
  sku text,
  quantidade numeric,
  valor_unitario numeric,
  valor_total numeric,
  desconto numeric,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  unidade text,
  aliquota_ipi numeric DEFAULT 0,
  descricao_detalhada text,
  comissao_base numeric DEFAULT 0,
  comissao_aliquota numeric DEFAULT 0,
  comissao_valor numeric DEFAULT 0,
  natureza_operacao_id bigint,
  raw_data jsonb,
  preco_custo numeric DEFAULT 0
);

CREATE TABLE public.bling_products (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  bling_id bigint NOT NULL,
  nome text NOT NULL,
  codigo text,
  preco numeric,
  preco_custo numeric,
  estoque_atual numeric,
  estoque_minimo numeric,
  tipo text,
  situacao text,
  formato text,
  descricao_curta text,
  descricao_completa text,
  unidade text,
  peso_liquido numeric,
  peso_bruto numeric,
  gtin text,
  imagem_url text,
  categoria_id bigint,
  categoria_nome text,
  raw_data jsonb,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  synced_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  altura numeric,
  largura numeric,
  profundidade numeric,
  fornecedor_id integer,
  fornecedor_nome text,
  fornecedor_codigo text,
  marca text,
  imagens jsonb,
  variacoes jsonb,
  produto_pai_id bigint,
  ncm text,
  cest text,
  origem integer,
  tributacao jsonb,
  estoque_depositos jsonb,
  condicao integer,
  frete_gratis boolean DEFAULT false,
  producao_propria boolean DEFAULT false,
  observacoes text,
  localizacao text,
  cross_docking integer,
  garantia integer,
  volumes_por_produto integer,
  gtin_embalagem text,
  campos_customizados jsonb,
  data_validade date,
  classe_fiscal text,
  sob_encomenda boolean DEFAULT false,
  ean text,
  dados_nfe jsonb,
  UNIQUE(bling_id, integration_id)
);

CREATE TABLE public.bling_sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  sync_type text NOT NULL,
  status text DEFAULT 'pending',
  records_synced integer DEFAULT 0,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.bling_sync_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  sync_log_id uuid NOT NULL REFERENCES public.bling_sync_logs(id) ON DELETE CASCADE,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  job_type text NOT NULL,
  status text DEFAULT 'pending',
  current_page integer DEFAULT 0,
  total_count integer DEFAULT 0,
  processed_count integer DEFAULT 0,
  saved_count integer DEFAULT 0,
  error_message text,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  resume_page integer NOT NULL DEFAULT 1,
  max_pages_per_run integer NOT NULL DEFAULT 3,
  last_heartbeat_at timestamptz,
  attempts integer NOT NULL DEFAULT 0,
  locked_at timestamptz,
  locked_by text
);

CREATE TABLE public.bling_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  event_key text NOT NULL UNIQUE,
  tenant_id uuid REFERENCES public.tenants(id),
  company_id text NOT NULL,
  resource text NOT NULL,
  action text NOT NULL,
  payload jsonb NOT NULL,
  received_at timestamptz DEFAULT now(),
  processed_at timestamptz,
  status text DEFAULT 'received',
  error text
);
