-- =============================================================================
-- SPY PRO CRM - VPS DEPLOY: TABELAS MELHOR ENVIO
-- =============================================================================

CREATE TABLE public.melhor_envio_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE UNIQUE,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamptz NOT NULL,
  user_id text,
  user_name text,
  user_email text,
  environment text DEFAULT 'production',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.me_shipments (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  me_id text NOT NULL,
  order_id uuid,
  order_number text,
  protocol text,
  tracking_code text,
  service_name text,
  carrier text,
  status text DEFAULT 'pending',
  price numeric,
  discount numeric,
  insurance_value numeric,
  format text,
  weight numeric,
  width integer,
  height integer,
  length integer,
  receipt boolean DEFAULT false,
  own_hand boolean DEFAULT false,
  collect boolean DEFAULT false,
  from_address jsonb,
  to_address jsonb,
  tracking_events jsonb DEFAULT '[]',
  last_tracking_at timestamptz,
  posted_at timestamptz,
  delivered_at timestamptz,
  canceled_at timestamptz,
  expired_at timestamptz,
  raw_data jsonb,
  synced_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  invoice jsonb,
  volumes jsonb,
  tags jsonb,
  authorization_code text,
  quote numeric,
  products jsonb,
  paid_at timestamptz,
  generated_at timestamptz,
  print_url text,
  preview_url text,
  delivery_min integer,
  delivery_max integer,
  estimated_delivery_at timestamptz,
  sender_name text,
  receiver_name text,
  receiver_phone text,
  receiver_city text,
  receiver_state text,
  receiver_address jsonb,
  dimensions jsonb,
  last_sync_at timestamptz DEFAULT now(),
  external_order_number text,
  li_order_id uuid REFERENCES public.li_orders(id),
  sender_document text,
  sender_email text,
  sender_phone text,
  receiver_email text,
  receiver_document text,
  receiver_note text,
  agency_name text,
  agency_address jsonb,
  cte_key text,
  contract text,
  billed_weight numeric,
  non_commercial boolean DEFAULT false,
  conciliation jsonb,
  additional_info jsonb,
  service_details jsonb,
  financial_details jsonb,
  integration_id uuid REFERENCES public.integrations(id),
  bling_order_id uuid REFERENCES public.bling_orders(id),
  UNIQUE(tenant_id, me_id)
);

CREATE TABLE public.me_sync_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  integration_id uuid REFERENCES public.integrations(id),
  status text NOT NULL DEFAULT 'pending',
  current_page integer DEFAULT 1,
  total_pages integer,
  items_saved integer DEFAULT 0,
  items_total integer,
  items_linked integer DEFAULT 0,
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  cursor_data jsonb DEFAULT '{}'
);

CREATE TABLE public.me_auto_sync_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  integration_id uuid NOT NULL REFERENCES public.integrations(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  sync_type text NOT NULL DEFAULT 'shipments',
  is_active boolean NOT NULL DEFAULT false,
  interval_minutes integer NOT NULL DEFAULT 30,
  last_sync_at timestamptz,
  next_sync_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
