-- Increment email_campaigns counters whenever an email_events row is inserted.
-- Handles: open → total_opened, click → total_clicked
-- Other event types (bounce, complaint, unsubscribe, delivered) are handled
-- separately by the campaign-send / webhook flow — this trigger only covers
-- the two event types generated by our edge tracking functions.

CREATE OR REPLACE FUNCTION public.update_campaign_stats_on_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.event_type = 'open' THEN
    UPDATE email_campaigns
    SET total_opened = total_opened + 1
    WHERE id = NEW.campaign_id;
  ELSIF NEW.event_type = 'click' THEN
    UPDATE email_campaigns
    SET total_clicked = total_clicked + 1
    WHERE id = NEW.campaign_id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_email_event_campaign_stats
  AFTER INSERT ON email_events
  FOR EACH ROW
  EXECUTE FUNCTION public.update_campaign_stats_on_event();
